### ISSUE TITLE
Create interface to environment sensors

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/ethoscope#1]
_From @qgeissmann on February 4, 2015 16:42_

`Monitor` objects should be able to interface abstract/physical sensors(e.g. visible light sensor) and  query them at each iteration of `run()`. This would work well with the SQLite file writer as well as we could simply add a table for sensors.

_Copied from original issue: gilestrolab/pySolo-Video#22_

**Comment by ggilestro** [comment]
Commit https://github.com/gilestrolab/ethoscope/commit/7414ac6e46a3d89e7e31fbaf3a4a9823892ef5ff introduced an mDNS / zeroconf support for ESP32 based sensors, handled independently of ethoscopes.
