### ISSUE TITLE
tracking or streaming not starting due to special characters in code

### ISSUE THREAD

**Issue by pepelisu** [gilestrolab/ethoscope#106]
The error is this one:
``
Sorry there has been an error: Traceback (most recent call last): File "/opt/ethoscope-device/src/ethoscope/web_utils/record.py", line 290, in run self._info["experimental_info"] = ExpInfoClass(**exp_info_kwargs).info_dic File "/opt/ethoscope-device/src/ethoscope/web_utils/control_thread.py", line 41, in __init__ self._check_code(code) File "/opt/ethoscope-device/src/ethoscope/web_utils/control_thread.py", line 52, in _check_code raise Exception("Code contains special characters. Please use only letters, digits or -") Exception: Code contains special characters. Please use only letters, digits or -
No Debug Image
``
However I am not sure I understand the issue. I tried by setting up the locale in the ethoscopes that in the new image that bit is missing and there is no locale set. 

Any ideas?

**Comment by ggilestro** [comment]
Hi Luis - glad to have you back!
I think code is passed from the node, so maybe is a locale issue on the node?

Can you try adding verbosity to the logger on line 51 of `control_thread.py`?

```
                logging.error("the code in the video name contains unallowed characters: " % code)
```
