### ISSUE TITLE
Pluggable display for ethoscopes (enhancement)

### ISSUE THREAD

**Issue by antortjim** [gilestrolab/ethoscope#109]
Dear GilestroLab

I have noticed the ethoscopes don't send data to displays upon connection once the RPi is booted. The CLI is available only if the display is connected upon booting the RPi. However, I noticed that adding these two lines at the end of the `/boot/config.txt`:

```
hdmi_force_hotplug=1
hdmi_drive=2​
```
makes the RPi respond to the connection of the display and it sends data to it automatically. Is there a reason why these lines are not present in the ethoscope OS images? I have tried this and it causes no problem!

I found this following this guide: https://howtoraspberrypi.com/raspberry-pi-hdmi-not-working/

Best regards,
Antonio

**Comment by ggilestro** [comment]
Yes - you're correct. Thanks a lot for the suggestion.  I actually noticed the same earlier this week and I am adding this line to next version of the SD card indeed. It's only the first line that is needed (`hdmi_force_hotplug=1`). The second line is used to drive audio through HDMI and we do not need that.
