### ISSUE TITLE
/tmp folder gets full with ethoscope_* preview images

### ISSUE THREAD

**Issue by pepelisu** [gilestrolab/ethoscope#114]
If the node is not restarted in a long time, the `/tmp` folder gets full with ethoscope_* preview images. These images are created when previewing the video in the browser. 
Suggestion: Make a cron or regular script that deletes the ethoscope_* files on /tmp that are more than 1 minute old.

**Comment by ggilestro** [comment]
Thanks for pointing this out. I am considering recoding the whole preview procedure to replace it with an actual stream using the ZeroMQ protocol. This would stream previews as mjpg and solve a number of annoying issues like the one you just found.
