### ISSUE TITLE
Adding user data and issue with missing experiments

### ISSUE THREAD

**Issue by DenaFrancis** [gilestrolab/ethoscope#115]
Hi gilestro lab,
I am running the node from a RPI4 and I have updated the latest version of the node and ethoscope (from May). But I am having an issue with the management page of the node interface. It won't let me save the user information or save the path of where to put the data. However, I can save new incubator information. After typing in the user info, the save button is greyed out.
<img width="1270" alt="Screen Shot 2020-06-06 at 3 57 23 pm" src="https://user-images.githubusercontent.com/18545633/83937246-8c97f980-a80e-11ea-9394-19c8edd32505.png">

Also, I managed to run a pilot tracking experiment. I let it track for a few days, but I don't know where to find that data. I have a pic of the experiments, but nothing that goes for three days. 
<img width="1270" alt="Screen Shot 2020-06-06 at 12 50 17 pm" src="https://user-images.githubusercontent.com/18545633/83937132-73427d80-a80d-11ea-8cff-b23af0f83ddf.png">

Thanks!

**Comment by ggilestro** [comment]
Regarding the first issue (users). 
The first three fields are actually required even though PIN and email are not currently used. They will be used at some point to send notifications to users if there is a problem with the platform.
I have now changed the page to have some more explicit information about that.

![image](https://user-images.githubusercontent.com/696901/83974591-6e053180-a8e6-11ea-85a3-1ca53cb6b41e.png)

Regarding the second aspect: make sure your ethoscope-backup daemon is actually running.
Click on the gear under "management" and the first line should tell if your ethoscope backup is running or not.

**Comment by DenaFrancis** [comment]
Thank you for the fast response! 
For issue one: I have added the information into the fields, but it still won't save?
<img width="1270" alt="Screen Shot 2020-06-08 at 8 02 00 am" src="https://user-images.githubusercontent.com/18545633/83982593-32f91180-a96b-11ea-8421-b5bec77f542d.png">

For issue 2: I think that the backup daemon is active, at least in terms of what is displayed.

<img width="1270" alt="Screen Shot 2020-06-08 at 7 58 12 am" src="https://user-images.githubusercontent.com/18545633/83982611-69cf2780-a96b-11ea-9d61-c55ba3f4b0dc.png">
Thank you

**Comment by ggilestro** [comment]
For issue 1: try your full name - a username will be created for you (Dena Francis -> dfrancis)
For issue 2: I don't quite remember now how I configured the node on the rPi4. If the backup is active, you should be having data in the `/ethoscope_data/results` folder.

**Comment by DenaFrancis** [comment]
Issue 1: resolved. Thank you! 
Issue 2: I checked the ethosocope results files:

```
[root@ETHOSCOPE001 results]# du -hs /ethoscope_data/results/*
646M /ethoscope_data/results/00155fa83cc848019df1c9029bfb899f
14K	/ethoscope_data/results/001916f944d54aaa9b7743793dc0bd16
8.0K	/ethoscope_data/results/index.html
```
And on the node:
`[root@node node]# du -hs /ethoscope_data/*
8.0K	/ethoscope_data/results
4.0K	/ethoscope_data/tmp
601M	/ethoscope_data/videos
[root@node node]# du -hs /ethoscope_data/results/*
4.0K	/ethoscope_data/results/results_200527_003815.zip`

This file was created on a previous test, so it doesn't have the 3-day test results.

**Comment by ggilestro** [comment]
Hi Dena - 

Are you using an external hard drive to save the data? The rPI SD card is not large enough to be used for data storage. You should follow the manual and mount an external hard drive instead.
