### ISSUE TITLE
Cannot write 20200507_ethoscope_000 .img to sd card 32 GB of other brand

### ISSUE THREAD

**Issue by jfriaspt** [gilestrolab/ethoscope#118]
I'm trying to write 20200507 ethoscope 000.img to sd card 32 GB of other brand by using balenaEtcher software, but it fails because the sd card is slightly smaller (few mbs). 
Then I tried to build SD card the less easy way, but the version of tar.gz file is old one (20191108_ethoscope_000.tar.gz). It boots and apears in the node, but when I try to start a tracking experiment, it wont even start, stating an mysql error. 
This error is problably because I need a newer version compatible with the up to date node. 
Update the ethoscope fails also (stating "Software broken").

Finally, I tried to burn 20200507 ethoscope 000.img to a bigger sd card of 64 GB, and everything works fine (tracking, video recording, backup etc).

Is it possible to get a link with the up to date tar.gz file (not the img), to build sd card the less easy way?

Note: I even tried to shrink partitions on 64 GB sd card with gparted (like I did with the older versions), with the aim to make a new img file and then be capable of burning it to a 32 GB sd card, but this time is not working since the file system is f2fs.

best regards,

Jfrias

**Comment by ggilestro** [comment]
Dear Jfrias - I made another slightly smaller SD card today. You can download it from the usual [link](https://lab.gilest.ro:8001/resources). Hopefully this will work for you. 

Unfortunately, I need to migrate the entire manual at one point but for now, Instructions on how that was made can be found in my own notes [here](https://www.notion.so/giorgiogilestro/Maintain-ethoscope-SD-image-fe83714a43584c61960151745a2a9d99) and you should be able to reproduce for your own card.
