### ISSUE TITLE
No access to ethoscope settings fields

### ISSUE THREAD

**Issue by jfriaspt** [gilestrolab/ethoscope#120]
Do not have access to ethoscope settings (options - > settings). Not able to configure ethoscope id.

![no fields](https://user-images.githubusercontent.com/67520741/86301492-920e1700-bbf5-11ea-9afa-3f8e5a126802.jpg)
![log](https://user-images.githubusercontent.com/67520741/86301499-95090780-bbf5-11ea-86db-43b41873ea87.jpg)
![uptodate](https://user-images.githubusercontent.com/67520741/86302421-309b7780-bbf8-11ea-8913-2c7170e53e41.jpg)

The node is running on Virtualbox machine and detects ethoscope000. Before it worked, but after updates not anymore. I can configure ethoscope machine-name and hostname local files by ssh access and bypass this step, but after that not able to start tracking with similar issue (no options fields).  

![tracking](https://user-images.githubusercontent.com/67520741/86302339-e0241a00-bbf7-11ea-9325-a45ab6a58128.jpg)
![log2](https://user-images.githubusercontent.com/67520741/86302532-8e2fc400-bbf8-11ea-8f25-55c8247c9906.jpg)

I have no clue why this is happening. I'm a biologist and this is not my expertise. 
Btw the ethoscope project is really essential to the science community and I want to congratulate all developers envolved in this.

**Comment by ggilestro** [comment]
Thanks for pointing this out. This was a small bug on the ethoscope side. If you update your ethoscope, it will go away.

**Comment by ggilestro** [comment]
Fixed also in [today's SD image](https://imperialcollegelondon.box.com/shared/static/ckkhkaoor93xxwr4a0jb3c79htrhn7jy.zip).

**Comment by jfriaspt** [comment]
Thanks very much for the support! It works fine now .
