### ISSUE TITLE
Camera is not cleanly released after streaming video 

### ISSUE THREAD

**Issue by pepelisu** [gilestrolab/ethoscope#130]
If after streaming the video a tracking is starting one get the error of empty queue for devices. A restart solves the problem.

**Comment by ggilestro** [comment]
The problem appears to be with this line:

https://github.com/gilestrolab/ethoscope/blob/013c1cd38a21c958cca7f4b55ed1bd1b3830cbb5/src/ethoscope/web_utils/record.py#L122-L125

`serve_forever` does not start a thread and the process never leaves that if statement, so it cannot be stopped and the camera is not released. I am working to fix it.

**Comment by ggilestro** [comment]
This is now fixed. Please note that I completely changed the way we handle streaming so one needs to upddate both the ethoscope AND the node.
