### ISSUE TITLE
tolerances motor cover & motor holder - new SD module

### ISSUE THREAD

**Issue by rjs360** [gilestrolab/ethoscope#133]
Just checking before I make some slight modifications to the STLs: is anyone else having tolerance issues with 3d printed motor covers not fitting on the motor holder part (unless you want to hammer them in place without the possibility of removing them easily)?  I am referring to the sleep deprivation module parts that are described here: https://www.notion.so/New-modular-structure-and-new-electronics-a478fcbff07c469db1b531a7f50d336d 

I am printing on a not-so-high-end Creality3D Ender 3, but never had any issues with tolerances of the previous installments of the ethoscope parts.  Thanks for any feedback.

**Comment by ggilestro** [comment]
In what orientation are you printing the cover?
It should be printed in this way:

![image](https://user-images.githubusercontent.com/696901/95432123-26e78580-0946-11eb-96fa-89a20194457c.png)

**Comment by rjs360** [comment]
Yes, that is exactly the orientation in which I print them.  I tried another filament yesterday which was a bit better but still way too tight a fit to readily attach/remove.

**Comment by ggilestro** [comment]
You should expect hardly any friction. Perhaps try printing with a smaller nozzle setting (0.1 uM).

![ezgif com-gif-maker](https://user-images.githubusercontent.com/696901/95457978-7ee3b380-0969-11eb-8385-78885d4dee90.gif)

**Comment by rjs360** [comment]
Wow. That’s a big difference from the fit i am getting.  I will try the 0.1um setting but wondering now if one of my STL files may be a different version from what you show?

I exported the OnShape files as STL’s, is there another repository of the new SD module files that I could try?

Ruud

**Comment by ggilestro** [comment]
[This](https://cad.onshape.com/documents/176e8d4c540a50da42228c84/w/6424211cdb0e416f2b1ce2a2/e/b17ba6f469b074872a2a1791) is the STL you should be printing.

**Comment by rjs360** [comment]
Yes, that’s the one I used.
I will try some things and let you know if I find out what’s going on.
-Ruud

**Comment by rjs360** [comment]
Looks like printing at 0.1mm layer height is a definite improvement on my end.
Not quite as smooth as your gif suggests, but I may be over-extruding just a bit (that may also explain why 0.2mm layers are making it almost impossible to get on manually without breaking things). I can manually secure and remove the covers now. Thanks Giorgio!
