### ISSUE TITLE
Are "gaps" in data normal?

### ISSUE THREAD

**Issue by IllustratedMan-code** [gilestrolab/ethoscope#136]
I have several gaps in my data as evidenced by the tile plot below. Is this normal? Can I consider it as 0 movement?
Thanks.

[tileplot.pdf](https://github.com/gilestrolab/ethoscope/files/5440149/tileplot.pdf)

**Comment by ggilestro** [comment]
No, that does not look normal. without looking at the database file this looks like it could be something on rethomics side too. @qgeissmann do you have any idea?

**Comment by qgeissmann** [comment]
Hey, this basically means no data is available (`NA`). 
A priory, that could happen in one of several situations:

* the animal died/stopped moving for extended duration
* the animal escapes
* the animal is not detected, occluded, or leaves the region of interest

Using the snapshots embedded in the db file can help to debug these things.
I hope it helps!

**Comment by IllustratedMan-code** [comment]
The animal of interest are ticks which have long periods of inactivity. How extended of a duration would cause the gaps? Thanks

**Comment by IllustratedMan-code** [comment]
I am also using the custom ROI builder if that matters

**Comment by ggilestro** [comment]
Closing for lack of further activity.
