### ISSUE TITLE
Videos>Start streaming issue

### ISSUE THREAD

**Issue by rjs360** [gilestrolab/ethoscope#137]
Not sure if this is a new issue, but I couldn't find a previous report that was similar:

When I start streaming (not tracking) video from my three ethoscopes, I only receive a blank square as feedback, and when I then stop the streaming, it asks if I want to stop tracking (?), and if I confirm, the page hangs on "stopping streaming" (plus a blue button stating "stopping"). When I close this streaming tab, the ethoscope is still listed but as "stopping", and no stop/start icon next to the name of the ethoscope.

Also, this process does not seem to throw an error in the log?

When I instead initiate tracking, things seem to be working better.

Running latest Node and Ethoscope images, Manjaro Linux.
Any insight would be most appreciated.

**Comment by rjs360** [comment]
For good measure, here are some screen shots of what happens:

Initial list of devices:
![IMG_8882](https://user-images.githubusercontent.com/6621510/99158904-daf6d180-26a5-11eb-8fff-e2d5990ab3de.jpg)

After starting a stream on one device:
![IMG_8885](https://user-images.githubusercontent.com/6621510/99158893-cd414c00-26a5-11eb-9d49-5b558a916ced.jpg)

After stopping the stream tab on that device:
![IMG_8887](https://user-images.githubusercontent.com/6621510/99158841-468c6f00-26a5-11eb-9346-1a9527c4ed31.jpg)

After refreshing the tab (after stopping the stream):
![IMG_8888](https://user-images.githubusercontent.com/6621510/99158819-0af1a500-26a5-11eb-9aa9-1de59308e297.jpg)

After closing the (now frozen) streaming tab:
![IMG_8889 2](https://user-images.githubusercontent.com/6621510/99158809-f44b4e00-26a4-11eb-84f1-28ae04bac83e.jpg)

**Comment by ggilestro** [comment]
Hi - can you confirm which versions of the software you're running, please?
This definitely works with the latest dev but I'll probably merge to master by the end of November anyway.

**Comment by rjs360** [comment]
Hi Giorgio,

That would be for the node: manjaro-ethoscope-20.0.1-stable-minimal-x86_64.iso
And for the ethoscopes: 20201110_ethoscope_000.zip

Ruud

**Comment by ggilestro** [comment]
What version are you running on the node? You can go to the updater page and check the current version.

![image](https://user-images.githubusercontent.com/696901/99291268-73708b80-2837-11eb-983e-e132d49a7257.png)

**Comment by rjs360** [comment]
Sorry that’s:[dev] 20a8ed… (20-10-29 20:01:46)

-Ruud

**Comment by rjs360** [comment]
Hi Giorgio, thanks again for the follow-up. This now seems to be resolved (not sure how exactly though?).
