### ISSUE TITLE
A date and time range in which the device will perform

### ISSUE THREAD

**Issue by posttenebre** [gilestrolab/ethoscope#144]
I am wondering what the date and time range format is for this section. The url given is no longer active, and the code does not mention it either. Thanks in advance. 

![Screenshot 2021-01-26 at 19 06 52](https://user-images.githubusercontent.com/25460839/105885673-b6a26400-6009-11eb-8044-d4cfe91147a2.png)

**Comment by posttenebre** [comment]
I took a closer look at the code and determined that it should be something along the lines of
`2020-01-28 20:00:00 > 2020-01-30 20:00:00`
Am I correct?

**Comment by ggilestro** [comment]
Yes, you are correct. Apologies for the slow reply.

**Comment by posttenebre** [comment]
No worries. Should have looked deeper in the code initially. Will the manual for using the ethoscopes be available again soon?
