### ISSUE TITLE
How to obtain Index file?

### ISSUE THREAD

**Issue by zzaidi148** [gilestrolab/ethoscope#148]
Hello, 

I am terribly sorry for my incessant questions; I am totally new to all of this. I was just wondering how I could access the index files so as to input and analyze data in RStudio. I tried activating the script (make_index.py), however, it was not able to find my file of interest and create the index file for it. I also do not find it in my node interface. Any help would be appreciated!

![IMG_1681](https://user-images.githubusercontent.com/78026312/107546381-e9179980-6b91-11eb-8d0c-fce7793e242b.jpg)

**Comment by ggilestro** [comment]
the script `make_index.py` is found in the folder `/opt/ethoscope-node/node_src/scripts`

To run it, you will have to first navigate to that folder.
```
cd /opt/ethoscope-node/node_src/scripts
./make_index.py
```
A good way to make the index automatically is to copy the script to `/etc/cron.hourly/` and then activate the cronie service with `systemctl enable cronie; systemctl start cronie`

This will run the script for you automatically once every hour.
