### ISSUE TITLE
Running Ethoscope without a node

### ISSUE THREAD

**Issue by roaldarbol** [gilestrolab/ethoscope#166]
Hi! I've just come across Ethoscope and though I haven't yet tried it out, I must say I'm super impressed! 
I've been doing recordings of various smaller insects, mostly ants and ground beetles, in a setup that looks very similar (RPi controlled, IR lighting, camera above), but without the need to do high-throughput recordings yet. 
As I use the RPi as my "node" and data collector, I was wondering if it is somehow possible to run Ethoscope on the Pi alone, i.e. without the need of a node? 
The real-time tracking would be great for closed-loop experiments (as you obviously know), and if it would be sufficient to install the `python` package it would be much more suitable for a small lab like mine, while also making it easier bringing it out in the field as there's no reliance on wireless connections. :-) 
Thanks!

**Comment by ggilestro** [comment]
If you download the RPI4 image you just need to burn it on an SD card and you'll have a node ready to go.
[The latest commit](https://github.com/gilestrolab/ethoscope/commit/77a99156202c7c458e313f9ca960b5a61743e494) also adds some further options for controlling activities without using a node. See the ethoclient.py file for the actual code.
```
python ethoclient.py -s 192.168.1.125 -c stop
```
