### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by roaldarbol** [gilestrolab/ethoscope#167]
Very brief and minor issue, all the links on the [Introduction page](https://www.notion.so/Introduction-a1515a7ece82410e9befe39188095f94) of the documentation are broken/leads nowhere.

**Comment by ggilestro** [comment]
That page looks inactive to me. The documentation starts from [this point](https://www.notion.so/giorgiogilestro/Ethoscope-User-Manual-a9739373ae9f4840aa45b277f2f0e3a7), and it's best accessed through the main ethoscope portal: http://lab.gilest.ro/ethoscope
