### ISSUE TITLE
Ethoscope dimensions

### ISSUE THREAD

**Issue by roaldarbol** [gilestrolab/ethoscope#168]
I've been trawling through the documentation, but haven't figured out what the actual dimensions are - I've tried briefly using onshape, but I think learning a new software just to find dimensions seems a bit excessive (I use OpenSCAD for making CAD files). For now, for me, the most important aspect is 1) the length and width of the slide-in modules, and 2) distance between camera and module to ensure my design is perfectly compatible with what you've already developed. 
But maybe you could add a technical drawing to the documentation (if you have one).  :-)
Thanks!

**Comment by ggilestro** [comment]
I have add technical drawings directly to onshape, [here](https://cad.onshape.com/documents/176e8d4c540a50da42228c84/w/6424211cdb0e416f2b1ce2a2/e/c83c481531a3b9473785b901). 

The manual, which contains many more details, can be found [here](https://www.notion.so/giorgiogilestro/Ethoscope-User-Manual-a9739373ae9f4840aa45b277f2f0e3a7)
