### ISSUE TITLE
Database File structure incorrect?

### ISSUE THREAD

**Issue by BrainFriedLab** [gilestrolab/ethoscope#189]
Hi there,

I'm so close to getting rethomics working, I can taste it. BUT, I've found a weird problem with the .db files that is holding me up. Below is a comparison between the database file structures of my .db file (left) and your rethomics ethoscope .db file (right). The csv table is aokay looking. But it's missing tables for all of the ROIs and missing "Start events" and "Var_map" tables which is preventing me from loading up the data into rethomics.

<img width="854" alt="image" src="https://github.com/gilestrolab/ethoscope/assets/83838561/743431a1-144c-4608-b4e2-3a151eab3280">

**Comment by BrainFriedLab** [comment]
Figured it out! I went back to more .db files. Turns out my other .db files are a-okay in terms of the tables that are in them. It's just this single one that doesn't have the tables correctly in there. Not sure how to add proper tables, but I've gotten through that error!

**Comment by ggilestro** [comment]
Good to hear!
