### ISSUE TITLE
SD Module not responding

### ISSUE THREAD

**Issue by Sid0li** [gilestrolab/ethoscope#196]
Hi, Im Santiago from Argentina ive been building ethoscopes this year and now I wanted to build a couple SD modules. Ive already soldered everything and charged the progam into the Arduino nano every but it does not respond to the commands that appear below the "Module control" section in the Ethoscope Manual. My question is, how do you talk with the module? I have the Arduino connected via USB to my computer and no serial connection is opening and sendig the commands through the Arduino serial monitor does nothing at all.
Im sure im just not getting how this is supposed to work, ive read the manual quite a lot and it doesent sink in. 
So I would be very pleased with any kind of help jaja

**Comment by ggilestro** [comment]
Hi @Sid0li - yes, you should be able to connect to the arduino driving the SD module using the arduino IDE. Just make sure that you have selected the right port for communication, the right board, the right speed (115200). Did you manage to upload the code on the Arduino without issues? If you did, then you should have no problems communicating with it. Just send the H (as in HELP) command and you should receive a message back. Hope this helps.

**Comment by ggilestro** [comment]
No prob. I don't actually remember if we are using the teaching capability at the moment. The idea was to have a protocol so that the ethoscope can learn about the abilities of a new machine without having those hard coded inside. Say you build your own new machine that does something and you want to integrate it with the UI, teaching could do that. But in all truth I don't remember whether this is something that I did to future proof the platform or whether I am already using it!

**Comment by Sid0li** [comment]
Ohh okay okay, so the teaching function is not intended for the Ethoscope right? The Ethoscope does already know how to interact with the module when you plug it in the USB port of the raspberry pi?
While i'm here let me ask you one more thing, about the motors and the way they rotate the tubes. Is it all done by friction between the silicon tubing in the motor shaft and the tube? I have the setup shown in the file attached but it doesnt rotate the tube consistently, any advice on how to improve this?
![Motorcito y tubo](https://github.com/user-attachments/assets/ad563ecc-72b5-417d-a7ea-5fda958ff11f)

And thank so much for your help Giorgio!! <3

**Comment by ggilestro** [comment]
Yes, it should simply work by friction but depending on the printer you use, the position of the motor could be a fraction of a millimeter too down and lose grip. You could try using thicker silicon. Alternatively, I think someone made a little modification that uses a 3D printed glass cap in the shape of little gear that matches a larger gear installed on the motor. I don't remember if this was in the lab of Sha Liu at the VIB or whether it was Orie Shafer at Bloomington Uni.
