### ISSUE TITLE
Name experiments

### ISSUE THREAD

**Issue by estebanbeck** [gilestrolab/ethoscope#25]
Could be possible to give a name to the experiment when we start the ethoscopes? If this is a metadata then we can retrieve it in R.

**Comment by qgeissmann** [comment]
Good idea, this is now quite easy to do, with user options interface. then we can simply link the "experiment_name" in the metadata.

**Comment by qgeissmann** [comment]
Ok, so I co-opted the option parsing mechanism to get simply this:


![screenshot from 2015-11-30 15-08-51](https://cloud.githubusercontent.com/assets/1399684/11475285/6fdd47f0-9774-11e5-993c-470d6367c03a.png)

Also we display it in the device list table

![screenshot from 2015-11-30 15-09-06](https://cloud.githubusercontent.com/assets/1399684/11475284/6fd8ffce-9774-11e5-9721-a3b10804af03.png)

still need to make the table sortable (see #40)
