### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/ethoscope#71]
For publication, and actual use out of the lab, it would be nice to make a push on the doc.
At the moment, we have several places where info can be found about the ethoscope platform.
My experience is that this is crucial for adoption to have comprehensive material on websites:

This is how I see things working (preliminary version):

* The main page would live at http://gilestrolab.github.io/ethoscope it:
    * Showcases the platform with short video
    * Describes the main functionalities
    * Allows developers to make blog posts
    * Integrates social network activity 
    * Short technical overview (at least so people understand the concept of node, ethoscope, hardware, software, rethomics) with links to relevant parts
    * Link to authors/ collaborators/ related projects
    * Link to publications using Ethoscopes
* Ethoscope Wiki:
    * Description of the platform from a user perspective:
        * How to set an experiment
        * The functionality of the web interface
        * Date-time scheduler and other advanced things
        * link to rethomics (how to analyse the data)
    * Description of the platform from the maintainer point of view
        * How do I set up a device (link to hardware repo)
        * How do I set up a router
        * How do I set up a node
        * How do I set up an update system
        * How do I set up incremental backups and other useful scripts
    * From a  developer point of view
         * link to http://ethoscope.readthedocs.org/
         * setting up a testing/developing environment
    * Developing ethoscope hardware
        * link to hardware repo
* Rethomics mainpage
    * overview of the package
    * Tutorials (`knitR`)
    *  X links to ethoscope platoform/DAM/other behavioural platforms

**Comment by qgeissmann** [comment]
started that here https://github.com/gilestrolab/ethoscope/wiki

**Comment by qgeissmann** [comment]
Ok, so it is realistically a bit hard to work with wiki.
For large documentations, we do need a hierarchy rather that a collection of articles.
In addition, we would like to be able to print doc.
Altogether, I think we need something like gitbook.
I have created a layout for this project at https://www.gitbook.com/book/qgeissmann/ethoscope-manual/details
@ggilestro @pepelisu @estebanbeck and everyone interested in contributing, please link your github account to gitbook, so I invite you as collaborators.
After you have been invited, I suggest you download the gitbook desktop app (Arch users, it is on AUR), it work quite well.
I will start aggregating the doc from the different places this afternoon.

**Comment by qgeissmann** [comment]
@pepelisu any chance you help me rewriting the "Network" section:?   https://qgeissmann.gitbooks.io/ethoscope-manual/content/building-and-installation/node.html#network.
Did you do anything like it in you recent installation? Also, now,  the canonical way to set-up the network is to have a **wired** connection between node and router.

**Comment by pepelisu** [comment]
I can help you no problem. 
I will start reading what we have and make some changes.

**Comment by qgeissmann** [comment]
We are pretty advanced in terms of merging the doc from different parts. what we still have to do:
- [ ] add maintainer technical info
- [ ] enhance the doc with more images
- [ ] enable some gitbook plugins such as https://github.com/GitbookIO/plugin-algolia
- [ ] delete other type of doc (wiki, READMEs...)
- [ ]  make the [website](http://gilestrolab.github.io/ethoscope) nicer looking
