### ISSUE TITLE
date range picker raises exception

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/ethoscope#72]
A user got this error: 
![screenshot from 2016-11-08 15-35-43](https://cloud.githubusercontent.com/assets/1399684/20107330/0b6fa130-a5d0-11e6-9b59-98889876ffa8.png)

This is since merge with date-time picker. will try to fix it in `dev`. If cannot fix, will revert merge.

**Comment by ggilestro** [comment]
This should be fixed now. You can use the UI by clicking on the small icon on the right or alternatively you can interact with the textbox without UI as you did before. Clicking on the textbox will not prompt the UI anymore.
