### ISSUE TITLE
broken link to video in doc

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/ethoscope#79]
dead link in homepage of the doc: `http://gilestrolab.github.io/ethoscope/data/test_video.mp4`

**Comment by qgeissmann** [comment]
The new link is `https://imperialcollegelondon.box.com/v/ethoscope-test-video`

**Comment by ggilestro** [comment]
Let's avoid BOX for this. I have uploaded it on youtube
https://youtu.be/uGsWPLsU6ws

--
Giorgio F. Gilestro
http://gilest.ro

**Comment by qgeissmann** [comment]
Youtube may transcode videos, so it is likely to be a different one. Also, it is not obvious how to download video for local use...
