### ISSUE TITLE
device_server.py does not call the right app

### ISSUE THREAD

**Issue by selmalaki** [gilestrolab/ethoscope#91]
Shouldn't the run for cherryserver calls 'api' instead of 'app'?
app is a global variable and it is used in server.py so it calls another Bottle() which is used for the server.py 

When I changed 'app' to 'api' the  device_server.py runs with no errors.

**Comment by ggilestro** [comment]
`ethoscope/node_src/scripts/server.py` runs on the node, whereas `ethoscope/src/scripts/device_server.py` runs on the ethoscopes. There is no conflict in the namespace between the two.
