### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by pepelisu** [gilestrolab/ethoscope#92]
Python2.7 end of life is happening in January 1st 2020, The whole repository should be refactored and updated to work with python 3. 
For example MySQL-python is not longer working with python3 and mysql-connector is the suggested replacement. (check jannelia's fork).

**Comment by ggilestro** [comment]
Branch Python3.7 https://github.com/gilestrolab/ethoscope/tree/python3.7 is now fully functional. We will do a couple of weeks of beta testing on a parallel installation then merge to dev. Closing and placing under review.
